version: '3.3'
services:
  grav-nginx:
    build:
      context: ./1.3.0-rc.5
      dockerfile: Dockerfile
    container_name: grav
    environment:
      - USE_SSL=true
      - USE_SELF_GEN_CERT=true
    volumes:
      - "./html:/home/grav/www/html"
    ports:
      - "80:80"
      - "443:443"
